RUN printf "*               soft    core            unlimited\nroot            hard    core            unlimited\n" >>/etc/security/limits.conf
RUN mkdir /var/lib/systemd/coredump && chmod 777 /var/lib/systemd/coredump

